# Generated by Django 4.2.7 on 2024-01-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postattachment_post_attachments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
